title: ML4MS workshop
author: Sarath Menon

execute:
  execute_notebooks           : off

repository:
    url                       : https://github.com/pyiron-workshop/ML4MS-workshop
    path_to_book              : ""

launch_buttons:
  notebook_interface          : jupyterlab
  binderhub_url               : https://mybinder.org
